#!/bin/bash

contributors=( "Winnie Njoki"
		"Xanderyeng"
	)
echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications." > AUTHOR

for contributor in "${contributors[@]}"; do
	echo "$contributor" >> AUTHOR
done

echo "AUTHOR file generated successfully."
